server:
  port: 8080

spring:
  application:
    name: technical-test-fandi-sudrajat
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_fandi?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: my-secret-pw

  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
          create_namespaces: true
          format_sql: true
          jdbc:
            batch_size: 50
        jdbc:
          batch_size: 50
        jdbc_time_zone: UTC
        show_sql: true
        format_sql: true

api:
  keys:
    - key: test123
      role: ROLE_ADMIN
    - key: test456
      role: ROLE_CUSTOMER
    - key: test789
      role: ROLE_USER